### ISSUE TITLE
Being able to specify color for Stat.qq

### ISSUE THREAD

**Issue by juliohm** [GiovineItalia/Gadfly.jl#1429]
Currently, the option `color` is not supported when a layer includes the `Stat.qq` statistic. It would be nice to have the following two behaviours:

1. `color="red"` would simply mark the entire geometry with a fixed color.
2. `color=:column` would work like with other statistics.

Is it correct to say that (1) can be easily addressed? I don't know about (2).

**Comment by Mattriks** [comment]
The `Stat.qq` code looks quite old, and needs updating. 
1) Can be fixed by removing [this line](https://github.com/GiovineItalia/Gadfly.jl/blob/a23fcdc432bb4d3c4a3bfbe1a5e52021f6721ced/src/statistics.jl#L1560). 
I've also started #1430 to get feedback on the current color mapping syntax.

2) There's a couple of useful cases here:

+ two or more theoretical distributions, one sample
```julia
y = rand(Normal(), 100)
layer(x=[Normal(), LogNormal()], y=y, color=["N","LN"], Stat.qq, Geom.point)  
```

+ two or more samples (e.g. in df), one theoretical distribution
```julia
layer(df, x=[Normal()], y=:y, color=:column, Stat.qq, Geom.point)
```

I should try to implement both cases, but which case are you currently attempting?

**Comment by juliohm** [comment]
The use case I have in mind is two samples. I'd like to just color the qq
plot with arbitrary color. We found a solution with default_color but it
would be nice to be able to set it in place. Also color based on other
colors of the dataframe would be great.
