### ISSUE TITLE
CSV.jl in docs Project.toml

### ISSUE THREAD

**Issue by Mattriks** [GiovineItalia/Gadfly.jl#1509]
Does CSV.jl still need to be included in the docs [Project.toml](https://github.com/GiovineItalia/Gadfly.jl/blob/master/docs/Project.toml)?  It was introduced in #1283, but not removed in #1351.

**Comment by bjarthur** [comment]
doesn't appear to be.  the more deps we remove the better!  good catch.

**Comment by Mattriks** [comment]
What about [regen-precompiles.jl](https://github.com/GiovineItalia/Gadfly.jl/blob/master/test/regen-precompiles.jl), is it useful?

**Comment by bjarthur** [comment]
that was an attempt to reduce the first time to plot.  the recommended [workflow](https://timholy.github.io/SnoopCompile.jl/stable/#workflow) now is to use `@snoopi_deep` instead of `@snoop`, so it's a bit dated.  i'd suggest keeping this file for reference in case someone wants pick up the effort to reduce the JIT lag.
