### ISSUE TITLE
Histogram density y-values wrong in some cases

### ISSUE THREAD

**Issue by tlnagy** [GiovineItalia/Gadfly.jl#822]
For example, the following breaks the computation of the y-values:

``` .julia
using Gadfly
using Distributions
vals = rand(Normal(0, 1), 10000)
p = plot(x=vals/sum(vals), Geom.histogram(density=true))
draw(PNG("densityproblem.png", 20cm, 12cm), p)
```

![densityproblem](https://cloud.githubusercontent.com/assets/1661487/14393422/d57f5bc6-fd7b-11e5-8507-5f920e93e916.png)

**Comment by tlnagy** [comment]
This seems to be related to #574 and #781

**Comment by scidom** [comment]
Has there been any update on this?

**Comment by tlnagy** [comment]
None, sorry. I would be happy to review any PR if you want to tackle this, but I haven't had the time to track this one down.

**Comment by Jacob640** [comment]
I think this problem is due to the pull request that was introduced for #880. The fix replaced  the simultaneous assignment and element-wise division with separate operations thereby changing the precedence of the expression 

`bincounts ./= sum(bincounts) * binwidth`
to
`bincounts = bincounts ./ sum(bincounts) * binwidth`

Adding the brackets seems to do the trick

`bincounts = bincounts ./ (sum(bincounts) * binwidth)`

`plot(x=rand(Normal(), 1000), Geom.density, Geom.histogram(density=true))`
![image](https://cloud.githubusercontent.com/assets/1777669/22694310/9bf525b2-ed3e-11e6-9053-6cd671a78671.png)


I'll submit a pull request later

**Comment by tlnagy** [comment]
Thanks for looking into this! I'll be happy to review and merge if you submit a PR.

**Comment by bjarthur** [comment]
closed by https://github.com/GiovineItalia/Gadfly.jl/pull/977
