### ISSUE TITLE
Geom.bar position=:stack doesn't set y-axis maxvalue

### ISSUE THREAD

**Issue by gustafsson** [GiovineItalia/Gadfly.jl#826]
Example:

`plot(x=[1,1,2,2],y=[1,2,3,4],color=[1,2,1,2],Geom.bar(position=:stack))`

![screen shot 2016-04-20 at 12 48 20](https://cloud.githubusercontent.com/assets/184952/14672149/41bc2480-06f6-11e6-93be-1d8730cf2e65.png)

When you zoom out you see that the maxvalue of the y-axis seems to have been initially set to `maximum(y)` instead of `maximum([sum(y[c.==color]) for c in color])`.

![screen shot 2016-04-20 at 12 48 44](https://cloud.githubusercontent.com/assets/184952/14672161/4a0a80a0-06f6-11e6-8212-47ed0ef4ff3c.png)

**Comment by daschw** [comment]
Also, there is some really strange behaviour with stacked bar charts and negative values:

`plot(x = [1; 1; 2; 2], y = [1; 2; -2; -1], color = [1; 2; 1; 2], Geom.bar)`

returns

![negbars](https://cloud.githubusercontent.com/assets/16589944/17777690/c5342276-6561-11e6-93c3-9ffd7fb79c8b.png)

**Comment by bjarthur** [comment]
the negative problem here should be fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1030.  please check it out and let me know if not.

the zoom problem should have been fixed by https://github.com/GiovineItalia/Gadfly.jl/pull/1021

please reopen this issue if the problems still persist.  thanks.
